### ISSUE TITLE
How to switch camera in surface view.

### ISSUE THREAD

**Issue by JaiMW** [fyhertz/libstreaming#119]

**Comment by ram10609601** [comment]
what is the solution for this?
I am getting this exception while trying to switch the camera.
ImageView click code:
private ImageView btnSwitchCamera;
btnSwitchCamera = (ImageView) findViewById(R.id.btnSwitch);
/* camera switch */ 
		btnSwitchCamera.setOnClickListener(new View.OnClickListener() {
			@Override
			public void onClick(View v) {
				try {
					mSession.switchCamera();
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});

Logcat:
12-10 23:11:16.250: W/System.err(2220): java.lang.RuntimeException: setParameters failed
12-10 23:11:16.251: W/System.err(2220): 	at android.hardware.Camera.native_setParameters(Native Method)
12-10 23:11:16.251: W/System.err(2220): 	at android.hardware.Camera.setParameters(Camera.java:1878)
12-10 23:11:16.251: W/System.err(2220): 	at net.majorkernelpanic.streaming.video.VideoStream.createCamera(VideoStream.java:591)
12-10 23:11:16.251: W/System.err(2220): 	at net.majorkernelpanic.streaming.video.VideoStream.startPreview(VideoStream.java:312)
12-10 23:11:16.251: W/System.err(2220): 	at net.majorkernelpanic.streaming.video.VideoStream.switchCamera(VideoStream.java:135)
12-10 23:11:16.251: W/System.err(2220): 	at net.majorkernelpanic.streaming.Session$8.run(Session.java:597)
12-10 23:11:16.251: W/System.err(2220): 	at android.os.Handler.handleCallback(Handler.java:739)
12-10 23:11:16.251: W/System.err(2220): 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-10 23:11:16.251: W/System.err(2220): 	at android.os.Looper.loop(Looper.java:148)
12-10 23:11:16.251: W/System.err(2220): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by sbaar** [comment]
You need to go through the methods called when switch camera is called and remove the checks that stop the stream before the camera is flipped.
