### ISSUE TITLE
Callback buffer was too small - Samsung Galaxy Note 8, android 4.4.2

### ISSUE THREAD

**Issue by MattFL** [fyhertz/libstreaming#138]
On a Samsung Galaxy Note 8 with android 4.4.2, I'm attempting to stream video FROM the device via RTSP, and after many hours I'm stumped.  The most obvious error in the log is the error below:  

 _**E/Camera-JNI(14803): Callback buffer was too small! Expected 115200 bytes, but got 38016 bytes!**_

From here it just falls apart.  My code is based on example 1.  I get an error trying to attach the log file so I copied what I think is the relevant part below *(10.40.3.133 is my tablet)*.  I would greatly appreciate any suggestions!  

```
E/RtspServer(14803): PLAY 10.40.3.133:8554/

D/RtspServer(14803): RTSP/1.0 200 OK

D/RtspServer(14803): Server: MajorKernelPanic RTSP Server

D/RtspServer(14803): Cseq: 5

D/RtspServer(14803): Content-Length: 0

D/RtspServer(14803): RTP-Info: url=rtsp://10.40.3.133:8554/trackID=1;seq=0

D/RtspServer(14803): Session: 1185d20035702ca

D/RtspServer(14803): 

D/ISecCameraHardware( 1936): preview callback started

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME E

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME X

E/Camera-JNI(14803): Callback buffer was too small! Expected 115200 bytes, but got 38016 bytes!

E/Camera-JNI(14803): Couldn't allocate byte array for JPEG data

E/VideoStream(14803): Symptom of the "Callback buffer was to small" problem...

E/Camera-JNI(14803): Null byte array!

I/MediaCodecInputStream(14803): {csd-1=java.nio.ByteArrayBuffer[position=0,limit=8,capacity=8], height=144, mime=video/avc, csd-0=java.nio.ByteArrayBuffer[position=0,limit=12,capacity=12], what=1869968451, width=176}

V/H264Packetizer(14803): SPS or PPS present in the stream.

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME E

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME X

E/Camera-JNI(14803): Callback buffer was too small! Expected 115200 bytes, but got 38016 bytes!

E/Camera-JNI(14803): Couldn't allocate byte array for JPEG data

E/VideoStream(14803): Symptom of the "Callback buffer was to small" problem...

E/Camera-JNI(14803): Null byte array!

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME E

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME X

E/Camera-JNI(14803): Callback buffer was too small! Expected 115200 bytes, but got 38016 bytes!

E/Camera-JNI(14803): Couldn't allocate byte array for JPEG data

E/VideoStream(14803): Symptom of the "Callback buffer was to small" problem...

E/Camera-JNI(14803): Null byte array!

D/SSRMv2:SIOP( 2368): SIOP:: AP = 380, Delta = 0

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME E

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME X

E/Camera-JNI(14803): Callback buffer was too small! Expected 115200 bytes, but got 38016 bytes!

E/Camera-JNI(14803): Couldn't allocate byte array for JPEG data

E/VideoStream(14803): Symptom of the "Callback buffer was to small" problem...

E/Camera-JNI(14803): Null byte array!

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME E

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME X

E/Camera-JNI(14803): Callback buffer was too small! Expected 115200 bytes, but got 38016 bytes!

E/Camera-JNI(14803): Couldn't allocate byte array for JPEG data

E/VideoStream(14803): Symptom of the "Callback buffer was to small" problem...

E/Camera-JNI(14803): Null byte array!

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME E

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME X

E/Camera-JNI(14803): Callback buffer was too small! Expected 115200 bytes, but got 38016 bytes!

E/Camera-JNI(14803): Couldn't allocate byte array for JPEG data

E/VideoStream(14803): Symptom of the "Callback buffer was to small" problem...

E/Camera-JNI(14803): Null byte array!

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME E

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME X

E/Camera-JNI(14803): Callback buffer was too small! Expected 115200 bytes, but got 38016 bytes!

E/Camera-JNI(14803): Couldn't allocate byte array for JPEG data

E/VideoStream(14803): Symptom of the "Callback buffer was to small" problem...

E/Camera-JNI(14803): Null byte array!

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME E

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME X

E/Camera-JNI(14803): Callback buffer was too small! Expected 115200 bytes, but got 38016 bytes!

E/Camera-JNI(14803): Couldn't allocate byte array for JPEG data

E/VideoStream(14803): Symptom of the "Callback buffer was to small" problem...

E/Camera-JNI(14803): Null byte array!

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME E

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME X

E/Camera-JNI(14803): Callback buffer was too small! Expected 115200 bytes, but got 38016 bytes!

E/Camera-JNI(14803): Couldn't allocate byte array for JPEG data

E/VideoStream(14803): Symptom of the "Callback buffer was to small" problem...

E/Camera-JNI(14803): Null byte array!

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME E

D/ShotSingle( 1936): CAMERA_MSG_PREVIEW_FRAME X

E/Camera-JNI(14803): Callback buffer was too small! Expected 115200 bytes, but got 38016 bytes!

D/SecCameraCoreManager( 1936): disableMsgType: 0x10

D/ISecCameraHardware( 1936): disable ongoing preview callbacks

V/MediaCodecInputStream(14803): No buffer available...

D/STATUSBAR-NetworkController( 2731): refreshSignalCluster - setNWBoosterIndicators(false)

D/STATUSBAR-NetworkController( 2731): refreshSignalCluster: data=0 bt=false

D/STATUSBAR-IconMerger( 2731): checkOverflow(440), More:false, Req:false Child:4

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

D/SensorService( 2368):   -0.9 -0.1 9.6

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

W/WifiP2pStateTracker( 2368): WifiP2pStateReceiver : android.net.wifi.LINK_CONFIGURATION_CHANGED

W/WifiP2pStateTracker( 2368): WifiP2pStateReceiver : android.net.wifi.LINK_CONFIGURATION_CHANGED

D/ConnectivityService( 2368): handleConnectivityChange: address are the same reset per doReset linkProperty[1]: resetMask=0

D/ConnectivityService( 2368): handleConnectivityChange: setting default proxy info 

D/ConnectivityService( 2368): updateSourceRoutes : no source routing conditions

D/ConnectivityService( 2368): handleConnectivityChange: address are the same reset per doReset linkProperty[1]: resetMask=0

D/ConnectivityService( 2368): handleConnectivityChange: setting default proxy info 

D/ConnectivityService( 2368): updateSourceRoutes : no source routing conditions

D/SensorService( 2368):   -0.9 -0.0 9.5

D/dalvikvm( 2368): GC_CONCURRENT freed 5293K, 23% free 28212K/36600K, paused 20ms+10ms, total 195ms

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

V/MediaCodecInputStream(14803): No buffer available...

D/STATUSBAR-NetworkController( 2731): onSignalStrengthsChanged signalStrength=SignalStrength: 99 -1 -1 -1 -1 -1 -1 31 -72 -7 300 -1 2147483647 gsm|lte 0x5 level=5

V/MediaCodecInputStream(14803): No buffer available...

D/SensorService( 2368):   -0.9 -0.1 9.5

E/Watchdog( 2368): !@Sync 483

D/SSRMv2:SIOP( 2368): SIOP:: AP = 380, Delta = 0

D/STATUSBAR-NetworkController( 2731): refreshSignalCluster - setNWBoosterIndicators(false)

D/STATUSBAR-NetworkController( 2731): refreshSignalCluster: data=0 bt=false

V/MediaCodecInputStream(14803): No buffer available...

D/STATUSBAR-IconMerger( 2731): checkOverflow(440), More:false, Req:false Child:4

E/RtspServer(14803): TEARDOWN 10.40.3.133:8554/

I/RtspServer(14803): Connection from 10.40.3.157

D/RtspServer(14803): RTSP/1.0 200 OK

D/RtspServer(14803): Server: MajorKernelPanic RTSP Server

D/RtspServer(14803): Cseq: 6

D/RtspServer(14803): Content-Length: 0

D/RtspServer(14803): 

E/RtspServer(14803): OPTIONS rtsp://10.40.3.133:8554/

D/SecCameraCoreManager( 1936): disableMsgType: 0x10

D/RtspServer(14803): RTSP/1.0 200 OK

D/RtspServer(14803): Server: MajorKernelPanic RTSP Server

D/RtspServer(14803): Cseq: 2

D/RtspServer(14803): Content-Length: 0

D/RtspServer(14803): Public: DESCRIBE,SETUP,TEARDOWN,PLAY,PAUSE

D/RtspServer(14803): 

E/RtspServer(14803): DESCRIBE rtsp://10.40.3.133:8554/

V/MediaCodecInputStream(14803): No buffer available...

D/H264Packetizer(14803): H264 packetizer stopped !

I/ACodec  (14803): [OMX.SEC.AVC.Encoder] Now Executing->Idle

I/ACodec  (14803): [OMX.SEC.AVC.Encoder] Now Idle->Loaded

I/ACodec  (14803): [OMX.SEC.AVC.Encoder] Now Loaded

I/ACodec  (14803):  [OMX.SEC.AVC.Encoder] Now uninitialized

D/SecCameraCoreManager( 1936): disableMsgType: 0x10

D/SecCameraCoreManager( 1936): disableMsgType: 0x10

D/SecCameraCoreManager( 1936): disableMsgType: 0x100

D/SecCameraCoreManager( 1936): stopPreview

D/SecCameraCoreManager( 1936): virtual void android::SecCameraCoreManager::stopPreview():stop IT Policy checking thread

I/EDMNativeHelperService( 2368): isCameraEnabled

W/CameraBase(14803): An error occurred while connecting to camera: 0

E/RtspServer(14803): Fail to connect to camera service

W/System.err(14803): net.majorkernelpanic.streaming.exceptions.CameraInUseException: Fail to connect to camera service

W/System.err(14803): 	at net.majorkernelpanic.streaming.video.VideoStream.openCamera(VideoStream.java:565)

W/System.err(14803): 	at net.majorkernelpanic.streaming.video.VideoStream.createCamera(VideoStream.java:575)

W/System.err(14803): 	at net.majorkernelpanic.streaming.video.H264Stream.testMediaCodecAPI(H264Stream.java:125)

W/System.err(14803): 	at net.majorkernelpanic.streaming.video.H264Stream.testH264(H264Stream.java:119)

W/System.err(14803): 	at net.majorkernelpanic.streaming.video.H264Stream.configure(H264Stream.java:111)

W/System.err(14803): 	at net.majorkernelpanic.streaming.Session.syncConfigure(Session.java:395)

W/System.err(14803): 	at net.majorkernelpanic.streaming.rtsp.RtspServer$WorkerThread.processRequest(RtspServer.java:463)

W/System.err(14803): 	at net.majorkernelpanic.streaming.rtsp.RtspServer$WorkerThread.run(RtspServer.java:406)

D/RtspServer(14803): RTSP/1.0 500 Internal Server Error

D/RtspServer(14803): Server: MajorKernelPanic RTSP Server

D/RtspServer(14803): Cseq: 3

D/RtspServer(14803): Content-Length: 0

D/RtspServer(14803): 

D/ShotSingle( 1936): stopPreview

V/ShotSingle( 1936): stopPreview(0)

D/ISecCameraHardware( 1936): stopPreview E

I/RtspServer(14803): Client disconnected
```

**Comment by MattFL** [comment]
OK I found the problem.  In VideoQuality.java, this line declares a resolution: 

public final static VideoQuality DEFAULT_VIDEO_QUALITY = new VideoQuality(320,240,20,500000);

The declared resolution sets a buffer size. If your device supports this resolution then you're fine.. BUT if your device does not support this device, then in determineClosestSupportedResolution() a new resolution will be set, requiring a different buffer size.  However the buffer size was already set by the default video quality, so the wheels fall off.  The quick and dirty solution is to be sure your DEFAULT_VIDEO_QUALITY is set to a resolution that your device supports.  The more involved solution is to make sure the buffers get resized when the resolution changes.
