### ISSUE TITLE
SurfaceHolder error

### ISSUE THREAD

**Issue by serpro** [fyhertz/libstreaming#152]
In some Samsung devices (Running Android 5 or 5.1)
Galaxy S2 (GT-I9100)3 
Galaxy S6 (zeroflte)2 
Galaxy S6 Edge (zerolte)2 
Galaxy Note5 (noblelte)

I'm getting this error:
java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface
	at android.opengl.EGL14._eglCreateWindowSurface(Native Method)
	at android.opengl.EGL14.eglCreateWindowSurface(EGL14.java:263)
	at net.majorkernelpanic.streaming.gl.SurfaceManager.eglSetup(SurfaceManager.java:155)
	at net.majorkernelpanic.streaming.gl.SurfaceManager.<init>(SurfaceManager.java:79)
	at net.majorkernelpanic.streaming.gl.SurfaceView.run(SurfaceView.java:134)
	at java.lang.Thread.run(Thread.java:818)

It seems to be just in Samsung devices as I'm testing with other brands and it works fine.

**Comment by Shanmugamsundarrajan** [comment]
I am getting this error  "java.lang.IllegalArgumentException: Make sure the SurfaceView or associated SurfaceHolder has a valid Surface " in Android 5.1.1
How to resolve this
