### ISSUE TITLE
The decoder did not decode anything on Marshmallow

### ISSUE THREAD

**Issue by alexbat98** [fyhertz/libstreaming#165]
I'm trying to get libstreaming work with Marshmallow. However, it doesn't encode anything.

```
12-30 15:45:05.168 797-1353/org.rupps.bearstream W/System.err: java.lang.RuntimeException: The decoder did not decode anything.
12-30 15:45:05.168 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.hw.EncoderDebugger.decode(EncoderDebugger.java:801)
12-30 15:45:05.168 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.hw.EncoderDebugger.debug(EncoderDebugger.java:247)
12-30 15:45:05.168 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.hw.EncoderDebugger.debug(EncoderDebugger.java:116)
12-30 15:45:05.168 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.testMediaCodecAPI(H264Stream.java:132)
12-30 15:45:05.168 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.testH264(H264Stream.java:119)
12-30 15:45:05.169 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.configure(H264Stream.java:111)
12-30 15:45:05.169 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.Session.syncConfigure(Session.java:395)
12-30 15:45:05.169 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.rtsp.RtspClient$2.run(RtspClient.java:242)
12-30 15:45:05.169 797-1353/org.rupps.bearstream W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
12-30 15:45:05.169 797-1353/org.rupps.bearstream W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
12-30 15:45:05.169 797-1353/org.rupps.bearstream W/System.err:     at android.os.Looper.loop(Looper.java:168)
12-30 15:45:05.169 797-1353/org.rupps.bearstream W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
12-30 15:45:05.205 797-1353/org.rupps.bearstream W/System.err: java.lang.RuntimeException: Failed to decode NALs from the encoder.
12-30 15:45:05.205 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.hw.EncoderDebugger.debug(EncoderDebugger.java:259)
12-30 15:45:05.205 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.hw.EncoderDebugger.debug(EncoderDebugger.java:116)
12-30 15:45:05.206 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.testMediaCodecAPI(H264Stream.java:132)
12-30 15:45:05.206 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.testH264(H264Stream.java:119)
12-30 15:45:05.206 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.video.H264Stream.configure(H264Stream.java:111)
12-30 15:45:05.206 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.Session.syncConfigure(Session.java:395)
12-30 15:45:05.206 797-1353/org.rupps.bearstream W/System.err:     at net.majorkernelpanic.streaming.rtsp.RtspClient$2.run(RtspClient.java:242)
12-30 15:45:05.206 797-1353/org.rupps.bearstream W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
12-30 15:45:05.206 797-1353/org.rupps.bearstream W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
12-30 15:45:05.206 797-1353/org.rupps.bearstream W/System.err:     at android.os.Looper.loop(Looper.java:168)
12-30 15:45:05.206 797-1353/org.rupps.bearstream W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
```

Here is how I'm doing it:
```
        Camera tmpC = Camera.open();
        List<Camera.Size> sizeList = tmpC.getParameters().getSupportedVideoSizes();
        tmpC.release();

        VideoQuality vq = new VideoQuality(sizeList.get(0).width, sizeList.get(0).height);

        mSession = SessionBuilder.getInstance()
                .setContext(ctx)
                .setAudioEncoder(SessionBuilder.AUDIO_AAC)
                .setAudioQuality(new AudioQuality(128000,44100))
                .setVideoEncoder(SessionBuilder.VIDEO_H264)
                .setVideoQuality(vq)
                .setSurfaceView(surfaceView)
                .setPreviewOrientation(90)
                .setCallback(this)
                .build();
```

Any suggestions?

**Comment by sbaar** [comment]
Which device are you using? Nexus 5, 6, and 7 2013 work on marshmallow for me. However, alot of weird devices, like a specific htc desire, suffer this problem. I think there's something wrong with the encoder debugger detection. We should really figure this out.

**Comment by alexbat98** [comment]
I tested it on my HTC One M8 with SkyDragon ROM.

**Comment by alexbat98** [comment]
I'm still unable to get it work. Tried different ROMs, but all I get is that error message and this strange screen.
![screenshot_20160105-105702](https://cloud.githubusercontent.com/assets/829678/12111954/58685c70-b3aa-11e5-982f-f30533a1aa2b.png)

**Comment by sbaar** [comment]
Is that the direct camera preview or after it's rendered in opengl? If it's
what's rendered in opengl then I would guess it's a hardware problem.

**Comment by alexbat98** [comment]
That's a camera preview. The picture is moving and I can recognize objects around. So, it is just a distorted image. When I click record button, everything freezes.

**Comment by sbaar** [comment]
Try using resolution 720 x 480. Looking at the android compatibility document, it's the only resolution guaranteed to be supported on all devices. I have a sneaking suspicion that this is what the default resolution should be for this library. I've ordered some devices in the mail that users are reporting problems on. I'll update if I find solutions.

**Comment by alexbat98** [comment]
That seems to be working for me. But the picture is rotated 90 degrees CCW no matter which preview orientation I set and in what order I pass width and height. Anyway, that's better than nothing. Thank you very much.

**Comment by yxnyxnyxnyxn** [comment]
@sbaar Is this issue solved?  I also met this issue when I use resolution 1920x1080

**Comment by sbaar** [comment]
There has been no work done on the library in a long time, so no. Are you getting this on 320 x 180
640 x 360 and 1280 x 720 too? On every resolution your camera supports?
