### ISSUE TITLE
One camera and multi connections.

### ISSUE THREAD

**Issue by wyounglee** [fyhertz/libstreaming#215]
When I tried to make multi connections, I got camera create error.
What is the best way to make multi connections?

06-01 13:25:04.782 13386-15183/com.lginnotek.ipcam_a W/CameraBase: An error occurred while connecting to camera: 0
06-01 13:25:04.788 13386-15181/com.lginnotek.ipcam_a E/RtspServer: Fail to connect to camera service
06-01 13:25:04.788 13386-15181/com.lginnotek.ipcam_a W/System.err: com.lginnotek.streaming.exceptions.CameraInUseException: Fail to connect to camera service
06-01 13:25:04.788 13386-15181/com.lginnotek.ipcam_a W/System.err:     at com.lginnotek.streaming.video.VideoStream.openCamera(VideoStream.java:581)
06-01 13:25:04.788 13386-15181/com.lginnotek.ipcam_a W/System.err:     at com.lginnotek.streaming.video.VideoStream.createCamera(VideoStream.java:592)
06-01 13:25:04.788 13386-15181/com.lginnotek.ipcam_a W/System.err:     at com.lginnotek.streaming.video.H264Stream.testMediaCodecAPI(H264Stream.java:126)
06-01 13:25:04.788 13386-15181/com.lginnotek.ipcam_a W/System.err:     at com.lginnotek.streaming.video.H264Stream.testH264(H264Stream.java:120)
06-01 13:25:04.788 13386-15181/com.lginnotek.ipcam_a W/System.err:     at com.lginnotek.streaming.video.H264Stream.configure(H264Stream.java:112)
06-01 13:25:04.788 13386-15181/com.lginnotek.ipcam_a W/System.err:     at com.lginnotek.streaming.Session.syncConfigure(Session.java:395)
06-01 13:25:04.789 13386-15181/com.lginnotek.ipcam_a W/System.err:     at com.lginnotek.streaming.rtsp.RtspServer$WorkerThread.processRequest(RtspServer.java:463)
06-01 13:25:04.789 13386-15181/com.lginnotek.ipcam_a W/System.err:     at com.lginnotek.streaming.rtsp.RtspServer$WorkerThread.run(RtspServer.java:406)

**Comment by sampatparas13** [comment]
@wyounglee any updates?
