### ISSUE TITLE
OutOfMemoryError after 2 days!!!!!!

### ISSUE THREAD

**Issue by htlinxcui** [fyhertz/libstreaming#297]
java.lang.OutOfMemoryError: Failed to allocate a 115212 byte allocation with 101896 free bytes and 99KB until OOM
	at net.majorkernelpanic.streaming.hw.NV21Convertor.convert(NV21Convertor.java:118)
	at net.majorkernelpanic.streaming.hw.NV21Convertor.convert(NV21Convertor.java:109)
	at net.majorkernelpanic.streaming.video.VideoStream$2.onPreviewFrame(VideoStream.java:475)
	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1115)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at net.majorkernelpanic.streaming.video.VideoStream$3.run(VideoStream.java:560)
	at java.lang.Thread.run(Thread.java:818)

**Comment by zaners123** [comment]
Was this running it as a streaming server or client?
