### ISSUE TITLE
example3 ,encodeWithMediaCodecMethod2,  createinputsurface() return null

### ISSUE THREAD

**Issue by jackfan00** [fyhertz/libstreaming#45]
I tried encodeWithMediaCodecMethod2 in HTC M8 device,
but it failed when I click recording, and I can not find the reason.
configurationis :  H264, 176x144, 
following is the detail log 

07-02 11:37:10.062: I/RtspClient(8391): RECORD rtsp://202.153.207.34:1935/jacklive/test.stream RTSP/1.0
07-02 11:37:10.062: I/RtspClient(8391): Range: npt=0.000-
07-02 11:37:10.062: I/RtspClient(8391): CSeq: 5
07-02 11:37:10.062: I/RtspClient(8391): Content-Length: 0
07-02 11:37:10.062: I/RtspClient(8391): Session: 925019696
07-02 11:37:10.062: I/RtspClient(8391): Authorization: Digest username="hodo_jack",realm="Streaming Server",nonce="6a43415836208e65df339760e13446fe",uri="rtsp://202.153.207.34:1935/jacklive/test.stream",response="5f19c9b02e323cedcf116c6c388a1a30"
07-02 11:37:10.062: I/RtspClient(8391): 
07-02 11:37:10.082: D/RtspClient(8391): Response from server line=RTSP/1.0 200 OK
07-02 11:37:10.082: D/RtspClient(8391): Response from server line=Range: npt=now-
07-02 11:37:10.082: D/RtspClient(8391): Response from server line=Session: 925019696;timeout=60
07-02 11:37:10.082: D/RtspClient(8391): Response from server line=Cseq: 5
07-02 11:37:10.082: D/RtspClient(8391): Response from server line=Server: Wowza Streaming Engine 4.0.4 build11775
07-02 11:37:10.082: D/RtspClient(8391): Response from server line=Cache-Control: no-cache
07-02 11:37:10.082: D/RtspClient(8391): Response from server line=
07-02 11:37:10.082: D/RtspClient(8391): Response from server: 200
07-02 11:37:10.082: D/libc(8391): [NET] getaddrinfo+,hn 14(0x3230322e313533),sn(),family 0,flags 4
07-02 11:37:10.082: D/libc(8391): [NET] getaddrinfo-, SUCCESS
07-02 11:37:10.082: D/jack-h264stream(8391): enter H264stream.configure
07-02 11:37:10.092: D/jack-videostream(8391): createCamera, camera preview size:176 x 144
07-02 11:37:10.092: D/jack-h264stream(8391): testMediaCodecAPI enter updateCamera
07-02 11:37:10.092: D/jack-videostream(8391): enter updateCamera, mUpdated=true,mQuality=176 x 144
07-02 11:37:10.092: D/MP4Config(8391): PPS: aM4G4g==
07-02 11:37:10.092: D/MP4Config(8391): SPS: Z0KAFNoLE6AbQoTU
07-02 11:37:10.092: D/VideoStream(8391): Video encoded using the MediaCodec API with a surface
07-02 11:37:10.092: D/jack-videostream(8391): createCamera, camera preview size:176 x 144
07-02 11:37:10.092: D/jack-videostream(8391): encodeWithMediaCodecMethod2 enter updateCamera
07-02 11:37:10.092: D/jack-videostream(8391): enter updateCamera, mUpdated=true,mQuality=176 x 144
07-02 11:37:10.922: D/VideoStream(8391): Actual framerate: 25
07-02 11:37:11.042: E/ACodec(8391): [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -2147483648
07-02 11:37:11.042: I/RtspClient(8391): TEARDOWN rtsp://202.153.207.34:1935/jacklive/test.stream RTSP/1.0
07-02 11:37:11.062: W/System.err(8391): java.lang.NullPointerException
07-02 11:37:11.062: W/System.err(8391):     at net.majorkernelpanic.streaming.gl.SurfaceManager.<init>(SurfaceManager.java:70)
07-02 11:37:11.062: W/System.err(8391):     at net.majorkernelpanic.streaming.gl.SurfaceView.addMediaCodecSurface(SurfaceView.java:105)
07-02 11:37:11.062: W/System.err(8391):     at net.majorkernelpanic.streaming.video.VideoStream.encodeWithMediaCodecMethod2(VideoStream.java:524)
07-02 11:37:11.072: W/System.err(8391):     at net.majorkernelpanic.streaming.video.VideoStream.encodeWithMediaCodec(VideoStream.java:400)
07-02 11:37:11.072: W/System.err(8391):     at net.majorkernelpanic.streaming.MediaStream.start(MediaStream.java:248)
07-02 11:37:11.072: W/System.err(8391):     at net.majorkernelpanic.streaming.video.VideoStream.start(VideoStream.java:279)
07-02 11:37:11.072: W/System.err(8391):     at net.majorkernelpanic.streaming.video.H264Stream.start(H264Stream.java:100)
07-02 11:37:11.072: W/System.err(8391):     at net.majorkernelpanic.streaming.Session.syncStart(Session.java:456)
07-02 11:37:11.072: W/System.err(8391):     at net.majorkernelpanic.streaming.Session.syncStart(Session.java:501)
07-02 11:37:11.072: W/System.err(8391):     at net.majorkernelpanic.streaming.rtsp.RtspClient$4.run(RtspClient.java:258)
07-02 11:37:11.072: W/System.err(8391):     at android.os.Handler.handleCallback(Handler.java:733)
07-02 11:37:11.072: W/System.err(8391):     at android.os.Handler.dispatchMessage(Handler.java:95)
07-02 11:37:11.072: W/System.err(8391):     at android.os.Looper.loop(Looper.java:157)
07-02 11:37:11.072: W/System.err(8391):     at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by ShinGyuRi** [comment]
You have the same problem, have you found a solution so far?
